language: java
before_install:
  - mvn install:install-file -Dfile=./external-repo/support-v4-19.1.0.jar -DgroupId=com.android.support -DartifactId=support-v4 -Dversion=19.1.0 -Dpackaging=jar
  # Install base Android SDK
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null; fi
  - wget http://dl.google.com/android/android-sdk_r23.0.2-linux.tgz
  - tar xzf android-sdk_r23.0.2-linux.tgz
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  #  addon-google_apis-google-16
  - android update sdk --filter platform-tools,android-8,extra-android-support,66,$ANDROID_SDKS --no-ui --force > /d
install: mvn install -DskipTests=true -Dgpg.skip=true
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
